In [2]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import functools

# Informacion hoteles por isla

In [3]:
maestro_cm28 = "../../../datos/CM28/maestro_cm28.csv"
maestro_cm28 = pd.read_csv(maestro_cm28)
maestro_cm28.describe()

,Anyo,Plazas,Plazas_por_isla,Perc_Plazas,Establecimientos,Alojativos_por_isla,Perc_Establecimientos,Plazas_prev,Plazas_por_isla_prev,Perc_Plazas_prev,Establecimientos_prev,Alojativos_por_isla_prev,Perc_Establecimientos_prev,max_anyo,total_establecimientos,total_plazas,total_establecimientos_prev,total_plazas_prev
count,8810.000000,8810.000000,8810.000000,8810.000000,8810.000000,8810.000000,8810.000000,8061.000000,8061.000000,8061.000000,8061.000000,8061.000000,8061.000000,8810.0,8810.000000,8810.000000,8275.000000,8275.000000
mean,2009.956981,961.665721,88298.601022,1.589012,13.886266,1347.176958,1.588839,974.847041,85789.241285,1.636419,10.126287,963.444362,1.613947,2019.0,6730.819069,427500.306697,5101.590695,420108.780906
std,5.873266,2791.033843,58396.588013,3.477609,72.130758,2002.922318,3.810312,2840.356048,57110.622440,3.549372,40.217750,1313.475195,3.738913,0.0,7250.332858,36743.992497,4967.357352,28602.905218
min,2000.000000,0.000000,979.000000,0.000000,1.000000,80.000000,0.010000,0.000000,979.000000,0.000000,1.000000,80.000000,0.010000,2019.0,2690.000000,368625.000000,2690.000000,368625.000000
25%,2005.000000,22.000000,11096.000000,0.030000,1.000000,459.000000,0.160000,21.000000,11031.000000,0.030000,1.000000,389.000000,0.170000,2019.0,3001.000000,404868.000000,3001.000000,404868.000000
50%,2010.000000,76.000000,129343.000000,0.240000,3.000000,623.500000,0.470000,71.000000,127471.000000,0.240000,3.000000,614.000000,0.480000,2019.0,3157.000000,422090.000000,3157.000000,421845.000000
75%,2015.000000,500.000000,135170.000000,1.220000,8.000000,904.000000,1.250000,496.000000,134586.000000,1.270000,8.000000,849.000000,1.310000,2019.0,5357.000000,428800.000000,3735.000000,428122.000000
max,2019.000000,32170.000000,172032.000000,33.540000,2179.000000,8930.000000,55.230000,32170.000000,172032.000000,33.540000,1867.000000,8930.000000,55.230000,2019.0,24992.000000,509424.000000,24992.000000,509424.000000

In [4]:
maestro_cm28.groupby(['Isla','Municipio','Modalidad']).count()

                                                   Unnamed: 0  Anyo  \
Isla      Municipio                 Modalidad
El Hierro Frontera                  Extrahotelera         109   109
                                    Hotelera               60    60
          Pinar de El Hierro (El)   Extrahotelera          56    56
                                    Hotelera               21    21
          Valverde                  Extrahotelera          80    80
...                                                       ...   ...
Tenerife  Tegueste                  Extrahotelera          25    25
                                    Hotelera                3     3
          Victoria De Acentejo (La) Extrahotelera          24    24
          Vilaflor                  Extrahotelera          25    25
                                    Hotelera               91    91

                                                   Clasificacion  Plazas  \
Isla      Municipio                 Modalidad
El Hierro Frontera                  Extrahotelera             89     109
                                    Hotelera                  60      60
          Pinar de El Hierro (El)   Extrahotelera             40      56
                                    Hotelera                  21      21
          Valverde                  Extrahotelera             60      80
...                                                          ...     ...
Tenerife  Tegueste                  Extrahotelera              5      25
                                    Hotelera                   3       3
          Victoria De Acentejo (La) Extrahotelera              4      24
          Vilaflor                  Extrahotelera              5      25
                                    Hotelera                  91      91

                                                   Plazas_por_isla  \
Isla      Municipio                 Modalidad
El Hierro Frontera                  Extrahotelera              109
                                    Hotelera                    60
          Pinar de El Hierro (El)   Extrahotelera               56
                                    Hotelera                    21
          Valverde                  Extrahotelera               80
...                                                            ...
Tenerife  Tegueste                  Extrahotelera               25
                                    Hotelera                     3
          Victoria De Acentejo (La) Extrahotelera               24
          Vilaflor                  Extrahotelera               25
                                    Hotelera                    91

                                                   Perc_Plazas  \
Isla      Municipio                 Modalidad
El Hierro Frontera                  Extrahotelera          109
                                    Hotelera                60
          Pinar de El Hierro (El)   Extrahotelera           56
                                    Hotelera                21
          Valverde                  Extrahotelera           80
...                                                        ...
Tenerife  Tegueste                  Extrahotelera           25
                                    Hotelera                 3
          Victoria De Acentejo (La) Extrahotelera           24
          Vilaflor                  Extrahotelera           25
                                    Hotelera                91

                                                   Establecimientos  \
Isla      Municipio                 Modalidad
El Hierro Frontera                  Extrahotelera               109
                                    Hotelera                     60
          Pinar de El Hierro (El)   Extrahotelera                56
                                    Hotelera                     21
          Valverde                  Extrahotelera                80
...                                                             ...
Tenerife  Tegueste                  Extrahotelera                25
                                    Hotelera                      3
          Victoria De Acentejo (La) Extrahotelera                24
          Vilaflor                  Extrahotelera                25
                                    Hotelera                     91

                                                   Alojativos_por_isla  \
Isla      Municipio                 Modalidad
El Hierro Frontera                  Extrahotelera                  109
                                    Hotelera                        60
          Pinar de El Hierro (El)   Extrahotelera                   56
                                    Hotelera                        21
          Valverde                  Extrahotelera                   80
...                                                                ...
Tenerife  Tegueste                  Extrahotelera                   25
                                    Hotelera                         3
          Victoria De Acentejo (La) Extrahotelera                   24
          Vilaflor                  Extrahotelera                   25
                                    Hotelera                        91

                                                   Perc_Establecimientos  \
Isla      Municipio                 Modalidad
El Hierro Frontera                  Extrahotelera                    109
                                    Hotelera                          60
          Pinar de El Hierro (El)   Extrahotelera                     56
                                    Hotelera                          21
          Valverde                  Extrahotelera                     80
...                                                                  ...
Tenerife  Tegueste                  Extrahotelera                     25
                                    Hotelera                           3
          Victoria De Acentejo (La) Extrahotelera                     24
          Vilaflor                  Extrahotelera                     25
                                    Hotelera                          91

                                                   max_anyo  \
Isla      Municipio                 Modalidad
El Hierro Frontera                  Extrahotelera       109
                                    Hotelera             60
          Pinar de El Hierro (El)   Extrahotelera        56
                                    Hotelera             21
          Valverde                  Extrahotelera        80
...                                                     ...
Tenerife  Tegueste                  Extrahotelera        25
                                    Hotelera              3
          Victoria De Acentejo (La) Extrahotelera        24
          Vilaflor                  Extrahotelera        25
                                    Hotelera             91

                                                   total_establecimientos  \
Isla      Municipio                 Modalidad
El Hierro Frontera                  Extrahotelera                     109
                                    Hotelera                           60
          Pinar de El Hierro (El)   Extrahotelera                      56
                                    Hotelera                           21
          Valverde                  Extrahotelera                      80
...                                                                   ...
Tenerife  Tegueste                  Extrahotelera                      25
                                    Hotelera                            3
          Victoria De Acentejo (La) Extrahotelera                      24
          Vilaflor                  Extrahotelera                      25
                                    Hotelera                           91

                                                   total_plazas
Isla      Municipio                 Modalidad
El Hierro Frontera                  Extrahotelera           109
                                    Hotelera                 60
          Pinar de El Hierro (El)   Extrahotelera            56
                                    Hotelera                 21
          Valverde                  Extrahotelera            80
...                                                         ...
Tenerife  Tegueste                  Extrahotelera            25
                                    Hotelera                  3
          Victoria De Acentejo (La) Extrahotelera            24
          Vilaflor                  Extrahotelera            25
                                    Hotelera                 91

[164 rows x 12 columns]

## clasificacion de hoteles

In [5]:

clasificacion   = maestro_cm28.groupby(['Isla','Municipio','Modalidad','Clasificacion'])['Plazas','Alojativos_por_isla']
clasificacion.describe().loc[:,(slice(None),['count','min','max'])]

/tmp/ipykernel_49435/1153159040.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  clasificacion   = maestro_cm28.groupby(['Isla','Municipio','Modalidad','Clasificacion'])['Plazas','Alojativos_por_isla']

                                                   Plazas               \
                                                    count   min    max
Isla      Municipio Modalidad     Clasificacion
El Hierro Frontera  Extrahotelera 1 llave            20.0  99.0  177.0
                                  2 llaves           20.0  91.0   91.0
                                  4 llaves           15.0   4.0    4.0
                                  Categoría única    20.0  31.0  418.0
                                  Cinco estrellas     7.0   4.0    4.0
...                                                   ...   ...    ...
Tenerife  Vilaflor  Hotelera      1 palmera          20.0  40.0   40.0
                                  Cuatro estrellas   16.0  42.0   42.0
                                  Dos estrellas      15.0  28.0   28.0
                                  Tres estrellas     20.0  32.0   32.0
                                  Una estrella       20.0  17.0   17.0

                                                   Alojativos_por_isla         \
                                                                 count    min
Isla      Municipio Modalidad     Clasificacion
El Hierro Frontera  Extrahotelera 1 llave                         20.0   80.0
                                  2 llaves                        20.0   80.0
                                  4 llaves                        15.0  106.0
                                  Categoría única                 20.0   80.0
                                  Cinco estrellas                  7.0  144.0
...                                                                ...    ...
Tenerife  Vilaflor  Hotelera      1 palmera                       20.0  549.0
                                  Cuatro estrellas                16.0  574.0
                                  Dos estrellas                   15.0  583.0
                                  Tres estrellas                  20.0  549.0
                                  Una estrella                    20.0  549.0


                                                       max
Isla      Municipio Modalidad     Clasificacion
El Hierro Frontera  Extrahotelera 1 llave            459.0
                                  2 llaves           459.0
                                  4 llaves           459.0
                                  Categoría única    459.0
                                  Cinco estrellas    459.0
...                                                    ...
Tenerife  Vilaflor  Hotelera      1 palmera         8930.0
                                  Cuatro estrellas  8930.0
                                  Dos estrellas     8930.0
                                  Tres estrellas    8930.0
                                  Una estrella      8930.0

[474 rows x 6 columns]

In [7]:
clasificacion= maestro_cm28.groupby(['Isla','Municipio','Modalidad','Clasificacion'])['Perc_Establecimientos']
clasificacion.describe()

                                                    count       mean  \
Isla      Municipio Modalidad     Clasificacion
El Hierro Frontera  Extrahotelera 1 llave            20.0   4.673000
                                  2 llaves           20.0   2.937500
                                  4 llaves           15.0   0.616000
                                  Categoría única    20.0  14.270500
                                  Cinco estrellas     7.0   0.401429
...                                                   ...        ...
Tenerife  Vilaflor  Hotelera      1 palmera          20.0   0.133000
                                  Cuatro estrellas   16.0   0.122500
                                  Dos estrellas      15.0   0.119333
                                  Tres estrellas     20.0   0.133000
                                  Una estrella       20.0   0.133000

                                                         std    min      25%  \
Isla      Municipio Modalidad     Clasificacion
El Hierro Frontera  Extrahotelera 1 llave           1.409924   1.74   4.1875
                                  2 llaves          1.209275   0.87   2.0925
                                  4 llaves          0.244008   0.22   0.4250
                                  Categoría única   5.391520  10.07  11.0875
                                  Cinco estrellas   0.176958   0.22   0.2550
...                                                      ...    ...      ...
Tenerife  Vilaflor  Hotelera      1 palmera         0.060184   0.01   0.1275
                                  Cuatro estrellas  0.063193   0.01   0.0800
                                  Dos estrellas     0.064083   0.01   0.0700
                                  Tres estrellas    0.060184   0.01   0.1275
                                  Una estrella      0.060184   0.01   0.1275

                                                       50%      75%    max
Isla      Municipio Modalidad     Clasificacion
El Hierro Frontera  Extrahotelera 1 llave            5.105   5.6650   6.25
                                  2 llaves           3.065   3.7900   5.00
                                  4 llaves           0.720   0.8050   0.94
                                  Categoría única   12.435  14.0550  27.67
                                  Cinco estrellas    0.370   0.5100   0.69
...                                                    ...      ...    ...
Tenerife  Vilaflor  Hotelera      1 palmera          0.160   0.1700   0.18
                                  Cuatro estrellas   0.160   0.1625   0.17
                                  Dos estrellas      0.160   0.1600   0.17
                                  Tres estrellas     0.160   0.1700   0.18
                                  Una estrella       0.160   0.1700   0.18

[474 rows x 8 columns]