In [3]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import functools

In [5]:
maestro_cm19 = "../../datos/CM19/maestro_cm19.csv"
evol_cm19 = "../../datos/CM19/evolucion_cm19.csv"
maestro_cm19_dt = pd.read_csv(maestro_cm19)
evol_cm19_dt = pd.read_csv(evol_cm19)

evol_cm19_clean = evol_cm19_dt.rename(columns = {'anyo_': 'anyo', 'mes_': 'mes'}, inplace = False)

combined_cm19_dt = pd.concat([maestro_cm19_dt, evol_cm19_clean])
combined_cm19_dt

,lugar,origen,anyo,mes,valor,valorPrev,indicador,dimension,ultima_fecha
0,Isla De Gran Canaria,Residentes en España,2021,5,17174.0,NaN,Viajeros,Zonas turísticas,202106
1,Isla De Gran Canaria,Residentes en España,2021,4,14839.0,NaN,Viajeros,Zonas turísticas,202106
2,Isla De Gran Canaria,Residentes en España,2021,3,16440.0,0.0,Viajeros,Zonas turísticas,202106
3,Isla De Gran Canaria,Residentes en España,2021,3,16440.0,2536.0,Viajeros,Zonas turísticas,202106
4,Isla De Gran Canaria,Residentes en España,2021,3,11741.0,0.0,Viajeros,Zonas turísticas,202106
...,...,...,...,...,...,...,...,...,...
34684,Valle Gran Rey,NaN,2011,12,180.0,NaN,Personal empleado,Puntos turísticos,202106
34685,Valle Gran Rey,NaN,2011,11,190.0,NaN,Personal empleado,Puntos turísticos,202106
34686,Valle Gran Rey,NaN,2011,9,187.0,NaN,Personal empleado,Puntos turísticos,202106
34687,Valle Gran Rey,NaN,2011,8,166.0,NaN,Personal empleado,Puntos turísticos,202106
34688,Valle Gran Rey,NaN,2011,7,172.0,NaN,Personal empleado,Puntos turísticos,202106

In [6]:
combined_cm19_filtered = combined_cm19_dt.drop_duplicates()
combined_cm19_filtered

,lugar,origen,anyo,mes,valor,valorPrev,indicador,dimension,ultima_fecha
0,Isla De Gran Canaria,Residentes en España,2021,5,17174.00,NaN,Viajeros,Zonas turísticas,202106
1,Isla De Gran Canaria,Residentes en España,2021,4,14839.00,NaN,Viajeros,Zonas turísticas,202106
2,Isla De Gran Canaria,Residentes en España,2021,3,16440.00,0.00,Viajeros,Zonas turísticas,202106
3,Isla De Gran Canaria,Residentes en España,2021,3,16440.00,2536.00,Viajeros,Zonas turísticas,202106
4,Isla De Gran Canaria,Residentes en España,2021,3,11741.00,0.00,Viajeros,Zonas turísticas,202106
...,...,...,...,...,...,...,...,...,...
34685,Valle Gran Rey,NaN,2011,11,190.00,NaN,Personal empleado,Puntos turísticos,202106
34686,Valle Gran Rey,NaN,2011,9,187.00,NaN,Personal empleado,Puntos turísticos,202106
34687,Valle Gran Rey,NaN,2011,8,166.00,NaN,Personal empleado,Puntos turísticos,202106
34688,Valle Gran Rey,NaN,2011,7,172.00,NaN,Personal empleado,Puntos turísticos,202106
16720,Oliva,NaN,2019,4,6.44,6.25,Estancia media,Puntos turísticos,202106

In [7]:
combined_cm19_filtered['ultima_fecha'] = pd.to_datetime(combined_cm19_filtered['ultima_fecha'], format='%Y%m')
combined_cm19_filtered

<ipython-input-7-a0ed311315d8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_cm19_filtered['ultima_fecha'] = pd.to_datetime(combined_cm19_filtered['ultima_fecha'], format='%Y%m')

,lugar,origen,anyo,mes,valor,valorPrev,indicador,dimension,ultima_fecha
0,Isla De Gran Canaria,Residentes en España,2021,5,17174.00,NaN,Viajeros,Zonas turísticas,2021-06-01
1,Isla De Gran Canaria,Residentes en España,2021,4,14839.00,NaN,Viajeros,Zonas turísticas,2021-06-01
2,Isla De Gran Canaria,Residentes en España,2021,3,16440.00,0.00,Viajeros,Zonas turísticas,2021-06-01
3,Isla De Gran Canaria,Residentes en España,2021,3,16440.00,2536.00,Viajeros,Zonas turísticas,2021-06-01
4,Isla De Gran Canaria,Residentes en España,2021,3,11741.00,0.00,Viajeros,Zonas turísticas,2021-06-01
...,...,...,...,...,...,...,...,...,...
34685,Valle Gran Rey,NaN,2011,11,190.00,NaN,Personal empleado,Puntos turísticos,2021-06-01
34686,Valle Gran Rey,NaN,2011,9,187.00,NaN,Personal empleado,Puntos turísticos,2021-06-01
34687,Valle Gran Rey,NaN,2011,8,166.00,NaN,Personal empleado,Puntos turísticos,2021-06-01
34688,Valle Gran Rey,NaN,2011,7,172.00,NaN,Personal empleado,Puntos turísticos,2021-06-01
16720,Oliva,NaN,2019,4,6.44,6.25,Estancia media,Puntos turísticos,2021-06-01

In [8]:
combined_cm19_filtered['lugar'] = combined_cm19_filtered['lugar'].fillna(value = 'NON-ID')
combined_cm19_filtered

<ipython-input-8-1cb851bd252d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_cm19_filtered['lugar'] = combined_cm19_filtered['lugar'].fillna(value = 'NON-ID')

,lugar,origen,anyo,mes,valor,valorPrev,indicador,dimension,ultima_fecha
0,Isla De Gran Canaria,Residentes en España,2021,5,17174.00,NaN,Viajeros,Zonas turísticas,2021-06-01
1,Isla De Gran Canaria,Residentes en España,2021,4,14839.00,NaN,Viajeros,Zonas turísticas,2021-06-01
2,Isla De Gran Canaria,Residentes en España,2021,3,16440.00,0.00,Viajeros,Zonas turísticas,2021-06-01
3,Isla De Gran Canaria,Residentes en España,2021,3,16440.00,2536.00,Viajeros,Zonas turísticas,2021-06-01
4,Isla De Gran Canaria,Residentes en España,2021,3,11741.00,0.00,Viajeros,Zonas turísticas,2021-06-01
...,...,...,...,...,...,...,...,...,...
34685,Valle Gran Rey,NaN,2011,11,190.00,NaN,Personal empleado,Puntos turísticos,2021-06-01
34686,Valle Gran Rey,NaN,2011,9,187.00,NaN,Personal empleado,Puntos turísticos,2021-06-01
34687,Valle Gran Rey,NaN,2011,8,166.00,NaN,Personal empleado,Puntos turísticos,2021-06-01
34688,Valle Gran Rey,NaN,2011,7,172.00,NaN,Personal empleado,Puntos turísticos,2021-06-01
16720,Oliva,NaN,2019,4,6.44,6.25,Estancia media,Puntos turísticos,2021-06-01

In [9]:
combined_cm19_filtered['valor'] = combined_cm19_filtered['valor'].fillna(value = 0)
combined_cm19_filtered['valorPrev'] = combined_cm19_filtered['valorPrev'].fillna(value = 0)
#En lugar de diferencias, se saca una nueva columna que pueda sacar el total de diferencias entre fechas en específico 
#en un periodo en especial
combined_cm19_filtered['valorDiff'] = combined_cm19_filtered['valor'] - combined_cm19_filtered['valorPrev']


print(combined_cm19_filtered.groupby('lugar', as_index=False)['valor'].sum())
print(combined_cm19_filtered.groupby('lugar', as_index=False)['valorPrev'].sum())
print(combined_cm19_filtered.groupby('lugar', as_index=False)['valorDiff'].sum())

                          lugar         valor
0                         Adeje  3.629087e+07
1                       Alajero  2.135601e+05
2                       Antigua  1.145784e+07
3                         Arona  5.212905e+07
4                    Breña Baja  3.787077e+06
5                      Frontera  3.843531e+05
6                         Mogán  3.938840e+07
7                         Oliva  1.120648e+07
8                        Pajara  1.156530e+07
9                     Paso (El)  5.908672e+05
10            Puerto De La Cruz  1.587818e+07
11    San Bartolomé De Tirajana  7.475739e+07
12          San Miguel De Abona  8.597936e+06
13   San Sebastian De La Gomera  4.027652e+05
14       Santa Cruz De La Palma  2.106210e+04
15           Santiago Del Teide  6.939605e+06
16                    Tazacorte  1.997883e+05
17                      Teguise  2.407384e+07
18                         Tias  4.641192e+07
19               Valle Gran Rey  3.907861e+06
20                        Yaiza  1.206990e+07
21        Isla De Fuerteventura  3.540249e+07
22         Isla De Gran Canaria  1.184220e+08
23               Isla De Hierro  4.732656e+05
24            Isla De La Gomera  4.723142e+06
25             Isla De La Palma  5.674643e+06
26            Isla De Lanzarote  8.810523e+07
27             Isla De Tenerife  1.216028e+08
28                        Oliva  6.440000e+00
                          lugar     valorPrev
0                         Adeje  3.570800e+07
1                       Alajero  2.023815e+05
2                       Antigua  1.143946e+07
3                         Arona  5.183710e+07
4                    Breña Baja  3.664339e+06
5                      Frontera  3.450596e+05
6                         Mogán  3.960506e+07
7                         Oliva  1.110173e+07
8                        Pajara  1.136140e+07
9                     Paso (El)  5.787529e+05
10            Puerto De La Cruz  1.563114e+07
11    San Bartolomé De Tirajana  7.432541e+07
12          San Miguel De Abona  8.467334e+06
13   San Sebastian De La Gomera  3.862301e+05
14       Santa Cruz De La Palma  1.285684e+04
15           Santiago Del Teide  7.051918e+06
16                    Tazacorte  1.800324e+05
17                      Teguise  2.408663e+07
18                         Tias  4.632043e+07
19               Valle Gran Rey  3.750316e+06
20                        Yaiza  1.204188e+07
21        Isla De Fuerteventura  3.515813e+07
22         Isla De Gran Canaria  1.183550e+08
23               Isla De Hierro  4.309555e+05
24            Isla De La Gomera  4.559613e+06
25             Isla De La Palma  5.487943e+06
26            Isla De Lanzarote  8.823776e+07
27             Isla De Tenerife  1.204637e+08
28                        Oliva  6.250000e+00
                          lugar   valorDiff
0                         Adeje   582867.14
1                       Alajero    11178.57
2                       Antigua    18376.40
3                         Arona   291945.85
4                    Breña Baja   122737.98
5                      Frontera    39293.44
6                         Mogán  -216655.55
7                         Oliva   104740.96
8                        Pajara   203891.31
9                     Paso (El)    12114.37
10            Puerto De La Cruz   247041.84
11    San Bartolomé De Tirajana   431979.19
12          San Miguel De Abona   130602.41
13   San Sebastian De La Gomera    16535.12
14       Santa Cruz De La Palma     8205.26
15           Santiago Del Teide  -112312.61
16                    Tazacorte    19755.87
17                      Teguise   -12796.44
18                         Tias    91491.38
19               Valle Gran Rey   157544.91
20                        Yaiza    28022.57
21        Isla De Fuerteventura   244353.27
22         Isla De Gran Canaria    67058.63
23               Isla De Hierro    42310.10
24            Isla De La Gomera   163529.38
25             Isla De La Palma   186700.93
26            Isla De Lanzarote  -132532.68
27             Isla De Tenerife  1139188.38
28                        Oliva        0.19

<ipython-input-9-7b79acde9c9f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_cm19_filtered['valor'] = combined_cm19_filtered['valor'].fillna(value = 0)
<ipython-input-9-7b79acde9c9f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_cm19_filtered['valorPrev'] = combined_cm19_filtered['valorPrev'].fillna(value = 0)
<ipython-input-9-7b79acde9c9f>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_cm19_filtered['valorDiff'] = combined_cm19_filtered['valor'] - combined_cm19_filtered['valorPrev']